= Javadoc parser documentation
:author: Christian Horz
:version: {project-version}
:source-highlighter: highlightjs

== About
This library can be used to parse Javadoc information from a plain java string.
The parser can be created by the following fluent API:

[source,java]
----
JavaDocParser parser = JavaDocParserBuilder
    .withBasicTags()
    .withOutputType(OutputType.PLAIN)
    .build();
----

All `Tags` that are registered as basic tags can be found in the package `com.github.chhorz.javadoc.tags.*`.
The creation of custom tags is described <<extensibility,here>>.

[source,java]
----
JavaDoc javaDoc = parser.parse(inputString); //<1>

List<AuthorTag> authors = javaDoc.getTags(AuthorTag.class); // <2>

AuthorTag authorTag = authors.get(0);
String authorName = authorTag.getAuthorName(); // <3>
----
<1> Parsing input string into a java object
<2> Reading a specific tag from `JavaDoc` object
<3> Getting information from the current tag

== Output format
In the future different output-formats will be supported.
At the moment the following output-formats with replacements can be used:
[cols="4*",options="header"]
|===
| Javadoc | Asciidoc | Markdown | HTML

| {@summary ...}
| ...
| ...
| ...

| {@code ...}
| \``...``
| \``...``
| <pre>...</pre>

| {@link ...}
3+| Currently no format replacement.

| {@linkplain ...}
3+| Currently no format replacement.

| {@literal ...}
| `\_..._`
| `\_..._`
| <i>...</i>

| {@value ...}
| \``...``
| \``...``
| <pre>...</pre>
|===

[[extensibility]]
== Extensibility
To extend the basic functionality of the Javadoc parser, the creation of an custom tag might be a good start.
All internal used basic Javadoc tags have the same structure.

[WARNING]
====
The parsing of custom should be tested with unit tests.
====

=== StructuredTag
This structured tags contain a list of segments separated with spaces.
Only the last segment can contain multiple words.

[source,java]
----
/**
 * @custom tagValue1 tagValue2
 */
public class CustomTag extends StructuredTag { // <1>

    private static final String TAG_NAME = "custom";
    private static final String TAG_VALUE_1 = "tagValue1";
    private static final String TAG_VALUE_2 = "tagValue2";

    public CustomTag() { // <2>
        super(TAG_NAME, TAG_VALUE_1, TAG_VALUE_2);
    }

    public String getTagValue1() {
        return getValues().get(TAG_VALUE_1);
    }

    // ...
}
----
<1> custom tags need to extend `com.github.chhorz.javadoc.tags.StructuredTag`
<2> super constructor has to be called with tag name and tag segments

After the creation of the custom Javadoc tag, the tag has to be registered at the parser.

[source,java]
----
JavaDocParser parser = JavaDocParserBuilder
    .withBasicTags()
    .withCustomTag(new CustomTag())
    .withOutputType(OutputType.PLAIN)
    .build();
----

Getting the custom tag date from the Javadoc works as shown above.

=== PatternTag
The `PatternTag` works similar to the `StructuredTag` but it is more flexible.
For tags of this kind, the Regex must be defined separately.
It is usable in more use-cases but more methods have to be implemented.

This example is based on the unit test for an `CustomPatternTag`.

[source,java]
----
/**
 * @custom number otherValue
 */
public class CustomPatternTag extends PatternTag { // <1>

    private static final String TAG_NAME = "custom";

    private static final String NUMBER = "number";
    private static final String OTHER_VALUE = "otherValue";

    private String number;
    private String otherValue;

    public CustomPatternTag() {
        super(TAG_NAME, "\\s+?(?<number>\\d+?)\\s+?(?<otherValue>.+?)\\s*"); // <2>
    }

    public Long getNumber(){
        return Long.parseLong(number);
    }

    public String getOtherValue(){
        return otherValue;
    }

    @Override
    public List<String> getSegmentNames() {
        return Arrays.asList(NUMBER, OTHER_VALUE);
    }

    @Override
    public void putValue(String segmentName, String value) {
        switch (segmentName) {
            case NUMBER:
                this.number = value;
            case OTHER_VALUE:
                this.otherValue = value;
        }
    }
}
----
<1> custom tags need to extend `com.github.chhorz.javadoc.tags.PatternTag`
<2> super constructor has to be called with tag name and custom regular expression

The registration on the `JavaDocParser` works the same way as for `StructuredTag`s.

== License
Spring Boot Monitor is Open Source software released under the link:http://www.apache.org/licenses/LICENSE-2.0.txt[Apache 2.0 license].
