= Javadoc parser documentation
:author: Christian Horz
:version: {project-version}
:source-highlighter: highlightjs

== About
This library can be used to parse Javadoc information from an plain java string.
The parser can be created by the following fluent api:

[source,java]
----
JavaDocParser parser = JavaDocParserBuilder
    .withBasicTags()
    .withOutputType(OutputType.PLAIN)
    .build();
----

All `Tags` that are registered as basic tags can be found in the package `com.github.chhorz.javadoc.tags.*`.
The creation of custom tags is described <<extendibility,here>>.

[source,java]
----
JavaDoc javaDoc = parser.parse(inputString); //<1>

List<AuthorTag> authors = javaDoc.getTags(AuthorTag.class); // <2>

AuthorTag authorTag = authors.get(0);
String authorName = authorTag.getAuthorName(); // <3>
----
<1> Parsing input string into Pojo
<2> Reading a specifict tag from `JavaDoc` object
<3> Getting information from the current tag

== Output format
In the future different output-formats will be supported.
Currently only `OutputType.PLAIN` is working.

[[extendibility]]
== Extendibility
To extend the basic functionality of the Javadoc parser, the creation of an custom tag might be a good start.
All internal used basic Javadoc tags have the same structure.

[source,java]
----
/**
 * @custom tagValue1 tagValue2
 */
public class CustomTag extends Tag { //<1>

    private static final String TAG_NAME = "custom";
    private static final String TAG_VALUE_1 = "tagValue1";
    private static final String TAG_VALUE_2 = "tagValue2";

    public CustomTag() { // <2>
        super(TAG_NAME, TAG_VALUE_1, TAG_VALUE_2);
    }

    public String getTagValue1() {
        return getValues().get(TAG_VALUE_1);
    }

    // ...
}
----
<1> custom tags need to extend `com.github.chhorz.javadoc.tags.Tag`
<2> super contstructor has to be called with tag name and tag segments

After the creation of the custom Javadoc tag, the tag has to be registered at the parser.

[source,java]
----
JavaDocParser parser = JavaDocParserBuilder
    .withBasicTags()
    .withCustomTag(new CustomTag())
    .withOutputType(OutputType.PLAIN)
    .build();
----

Getting the custom tag date from the Javadoc works as shown above.

[WARNING]
====
The parsing of custom should be tested with unit tests.
====

== License
Spring Boot Monitor is Open Source software released under the link:http://www.apache.org/licenses/LICENSE-2.0.txt[Apache 2.0 license].
