name: 'Java CI'

# on: [push, pull_request]

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - feature/**
      - dependabot/**
  workflow_dispatch:
    inputs:
      force_publish_snapshot:
        description: 'True to force publish a snapshot'
        required: true
        type: boolean

jobs:
  test:
    name: 'Build and test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against LTS version:
        java: [ 8, 11, 17 ]
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Set up JDK'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: jdk
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: 'Build with Maven'
        run: ./mvnw -V -B --no-transfer-progress install

  publish-snapshot:
    name: 'Publish snapshot'
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Set up JDK 8'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: jdk
          java-version: 8
          cache: 'maven'
          server-id: oss.sonatype.org
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: 'Publish snapshot'
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || ${{ github.event.inputs.force_publish_snapshot }}) && github.repository == 'chhorz/javadoc-parser'
        run: ./mvnw -B clean deploy --no-transfer-progress -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
