name: 'Release to Maven Central'

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
      new_development_version:
        description: 'Next development version'
        required: true

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Set up JDK'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: jdk
          java-version: 8
          cache: 'maven'
          server-id: oss.sonatype.org
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: 'Setup local git user'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: 'Perform deployment'
        run: |
          ./mvnw -B versions:set -DnewVersion=${{ github.event.inputs.release_version }}
          ./mvnw -B clean deploy --no-transfer-progress -Pcentral-deploy -DskipTests=true
          git add -u
          git commit -m "Update version to ${{ github.event.inputs.release_version }}"
          git tag v${{ github.event.inputs.release_version }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: 'Prepare next development version'
        run: |
          ./mvnw -B versions:set -DnewVersion=${{ github.event.inputs.new_development_version }}
          git add -u
          git commit -m "Update version to next development version ${{ github.event.inputs.new_development_version }}"

      - name: 'Commit and push changes'
        run: |
          git push
          git push origin v${{ github.event.inputs.release_version }}
